RADIUS_OF_INFLUENCE = 0.20
NUMBER_OF_AGENTS = 20
NUMBER_OF_FEATURES = 7
NODES_MOVEMENT_STEP = 0.01
RENDER_PAUSE = 0.001
TRAINING_PATH = 'graph_topologies/training_20/*'
TESTING_PATH = 'graph_topologies/testing_20/*'
